### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by JoshMcguigan** [JoshMcguigan/traffic#6]
Currently traffic uses [termion](https://github.com/redox-os/termion) for formatting the output. Termion is not compatible with Windows, which makes traffic not compatible with Windows. Since traffic only uses termion to bold the headings of the output, we should be able to develop a workaround for this.

**Comment by JoshMcguigan** [comment]
I would appreciate it if any Windows users could check out this branch and provide feedback.

```
git clone https://github.com/JoshMcguigan/traffic.git
cd traffic
git checkout windows-compatibility
cargo run
```

I just want to confirm the asci escape sequences in the output render correctly. On Windows, I'd say it's okay whether the font is actually bold or not, as long as there isn't a random `\x1B[1m` within the output.

**Comment by SebRut** [comment]
Seems to work:

```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
     Running `target\debug\traffic.exe`

Repository Name                               Unique Visits         Trend
                                              (last 14 days)

d2mm                                                3               Up 1 Day
traffic                                             1               None
jaspurrbot                                          1               None
greasemonkey-scripts                                1               None
robocodebots                                        1               None
robocode-info-unihro                                1               Up 1 Day
jankbot-modules                                     1               None
```

**Comment by SebRut** [comment]
Interestingly, if I run the compiled *.exes directory from shell and not via "cargo run" I get this: 

```
 .\traffic.exe

[1mRepository Name                               Unique Visits         Trend
                                              (last 14 days)
[0m
d2mm                                                3               Up 1 Day
traffic                                             1               None
jaspurrbot                                          1               None
greasemonkey-scripts                                1               None
robocodebots                                        1               None
robocode-info-unihro                                1               Up 1 Day
jankbot-modules                                     1               None
```

**Comment by JoshMcguigan** [comment]
Are you running both `cargo run` and the final `.exe` in powershell? That is surprising. Those escape sequences are meant to turn the headers bold. I think the `cargo run` result would be acceptable, but I'd like to find a fix for the issue when running the `.exe`. 

Feel free to submit a PR if you are able to figure something out. Worst case I think we can use conditional compilation to remove the asci escape sequences on windows.

**Comment by SebRut** [comment]
Yep, I'm running both in the same powershell. Maybe cargo sets some parameters internally for it's own display of data which leads to traffic output working right.

**Comment by JoshMcguigan** [comment]
@SebRut I pushed an update to that branch to conditionally disable the ansi escape sequences for Windows users, given the lack of support. Can you pull the latest changes and test again?

Thanks for the help!

**Comment by SebRut** [comment]
Seems to work fine!

**Comment by JoshMcguigan** [comment]
Windows is supported in the latest traffic release. Run `cargo install traffic --force` to get the latest version.
